name: Demo Workflow
on: workflow_dispatch
jobs:
  print:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello GitHub Actions!
      - name: Print a few lines
        run:
          echo first line
          echo second line
          
